---
- name: Git clone .ova template
  command: "git clone {{ ova_repo }}"
  args:
    chdir: "{{ path_to_ova }}"
  when: git_clone_ova==true

- name: "Create VM {{ vm_name }}"
  command: "vboxmanage import {{ path_to_ova }}/canaima-centos-template/canaima-centos-template.ova --vsys 0 --vmname {{ vm_name }} --memory {{ vm_memory }} --cpus {{ vm_cpus }}"

- name: "Start VM {{ vm_name }}"
  command: "VBoxManage startvm {{ vm_name }} --type headless"

- name: sleep for 60 seconds and continue with play
  wait_for: timeout=60

- name: "Generate correct /etc/hosts file on {{ vm_name }}" 
  lineinfile:
    path: /etc/hosts
    regexp: '^127.0.1.1'
    line: "127.0.1.1    {{ vm_name }}"
  delegate_to: "{{ template_ip }}"
  remote_user: ansible
  become: true

- name: "Generate correct /etc/hosts file on {{ vm_name }} (IPv6)" 
  lineinfile:
    path: /etc/hosts
    regexp: '^::1'
    line: "::1   {{ vm_name }}"
  delegate_to: "{{ template_ip }}"
  remote_user: ansible
  become: true

- name: "Set hostname to {{ vm_name }} in hostnamectl on {{ vm_name }}"
  command: "hostnamectl set-hostname {{ vm_name }}"
  delegate_to: "{{ template_ip }}"
  remote_user: ansible
  become: true

- name: "Set ip to {{ vm_ip }} on {{ vm_name }}"
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-enp0s3 
    regexp: '^IPADDR'
    line: "IPADDR={{ vm_ip }}"
  delegate_to: "{{ template_ip }}"
  remote_user: ansible
  become: true

- name: "Reboot {{ vm_name }}"
  reboot:
    reboot_timeout: 10
  delegate_to: "{{ template_ip }}"
  remote_user: ansible
  become: true
  ignore_errors: yes

- name: sleep for 100 seconds and continue with play
  wait_for: timeout=100
